### ISSUE TITLE
Customise Shortcuts and move mouse diagonally

### ISSUE THREAD

**Issue by reinhello** [darccyy/mousr-old#2]
**Is your feature request related to a problem? Please describe.**
Is it possible to customise the keybindings? I'm unable to type some letters, especially the one used to control the mouse (`WASD`, `IJKL`)

**Describe the solution you'd like**
A feature to customise the shortcuts.

**Describe alternatives you've considered**
One thing that I realised is that there's no control to move the mouse diagonally, is it possible to get this working? It'll be nice if (`I+J`) 
will move the mouse left diagonal. So as for the right diagonal movement.

**Additional context**
-

**Comment by darccyy** [comment]
Hi, thanks so much for using Mousr!

At the moment, the only way to change the shortcuts is to recompile with a different `shortcuts.json` file.
I am curious as to how you would like the feature implemented. Are you thinking a json file in the app directory? That might be the easiest way to implement and use it.

I will try to implement this feature, however I am having difficulty with the RobotJS package atm (You know how it is with Javascript).

You should be able to move the cursor diagonally by simultaneously pressing `I` and `J` (assuming you can).
Until this gets patched, creating an Autohotkey program might be a temporary fix.

(btw this might not get fixed for a while as I have exams)

**Comment by reinhello** [comment]
> Are you thinking a json file in the app directory? That might be the easiest way to implement and use it.

That's fine for me, would appreciate the feature implemented in any way. I need to change the shortcut because I'm unable to type some letters assuming they're used to control the cursor.

> You should be able to move the cursor diagonally by simultaneously pressing `I` and `J` (assuming you can).
Until this gets patched, creating an Autohotkey program might be a temporary fix.

Pressing `I` then `J` and again yeah, that moves the mouse diagonally but the movement isn't smooth and it makes it harder to navigate the cursor to a certain position.

**Comment by darccyy** [comment]
I see what you mean. I might in fact port this project to a different language like C++ or something.

**Comment by reinhello** [comment]
That would be great.

**Comment by reinhello** [comment]
Any update about this?

**Comment by darccyy** [comment]
Sorry, I have been very busy lately with school. I will try to soon.

**Comment by reinhello** [comment]
No worries at all, I can patiently wait

**Comment by darccyy** [comment]
As it turns out, this is very easy to create in AutoHotKey, so I will try to make it in that.

**Comment by darccyy** [comment]
I have created a new repository [here](https://github.com/darccyy/mousr) for the AHK version. It is still in uncompiled beta, but if you have AHK installed you can try it out.
I will add a shortcuts file soon, as well as build to exe or something, as well as fix bugs.
Hope this is better 👍

**Comment by reinhello** [comment]
Thanks! I'll try them out after school and give a proper feedback.

**Comment by darccyy** [comment]
In the meantime, do you mind filling out [this survey](https://bruh.news/survey)? It is for school.

**Comment by reinhello** [comment]
> In the meantime, do you mind filling out [this survey](https://bruh.news/survey)? It is for school.

Yeah, sure.

So here's my feedback (not very detailed but my honest opinion) regarding the new mousr:

- Looks like there are no significant changes (yet) but the new one looks better.

One thing that I'm still questioning and as this is still beta, will my feature request about having the mouse move smoothly acceptable?

I'm still struggling with having to get used to the mouse movement since it's too stiff for me (as shown in below video) 

https://user-images.githubusercontent.com/73813638/182311517-1d26b7dd-26c2-4343-892a-ee9de74135ad.mp4

**Comment by darccyy** [comment]
Ah, I see! This is a bug, it does not move like that on my machine. I will try to fix that. If building the source code, you can change the 'speed_duration' value to something higher if that works. Thanks.

**Comment by darccyy** [comment]
[Version 1.0.0](https://github.com/darccyy/mousr/releases/tag/v1.0.0) has now been released. If you have any issues with it, please open a new issue over there :) Smooth movement is still a bug that I will try to solve. Thanks for your support !

**Comment by reinhello** [comment]
Perfect, love this project. Keep up the work!
